### ISSUE TITLE
TASK-3.3: Set-Up the database for Reservations

### ISSUE THREAD

**Issue by irizhukova** [CosmicCoffeeCrew/CosmicCoffeeCrew-soen341projectW2024#31]
This task is for user story #2 .

- [x] Create the database for reservations with corresponding criteria (status, vehicle id, customer id, starting date, days rented, total price, rating, reservation id)

 
Low risk: setting up and running databases should be a simple task for us by now
High priority: this task will be built upon in the future and is crucial to maintain the websites order

**Comment by C4LIP0** [comment]
Done by Hossam and Enrique
