### ISSUE TITLE
AT-1.2: Search and Filter available cars

### ISSUE THREAD

**Issue by hossamgasser** [CosmicCoffeeCrew/CosmicCoffeeCrew-soen341projectW2024#80]
**Issue Tracking**
This acceptance test is for #1 
See the E2E test running here

**User Acceptance flow**
1. User inputs reservation start date, end date, and location
2. User is taken to a page with a car catolog matching search settings
3. There is an adjustable filter on the page to filter out car catalog as desired
4. Filter contains price settings, car type, and car color

**Comment by C4LIP0** [comment]
(https://drive.google.com/file/d/1ukEbvOtHVAtmV4ofiBDnNmU0_Eq4EOx0/view)

**Comment by C4LIP0** [comment]
[https://drive.google.com/file/d/1ukEbvOtHVAtmV4ofiBDnNmU0_Eq4EOx0/view?usp=sharing](url)
